jobs:
  test:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages
      - npm run test
orbs:
  node: 'circleci/node:x.y'
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test