jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - node/install-packages:
          cache-path: ~/project/api/node_modules
          override-ci-command: cd api && npm install
      - run: npm run start
      - run: npm run test
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test